# Generated by Django 3.2.7 on 2021-10-12 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('name', models.CharField(blank=True, max_length=191)),
            ],
        ),
        migrations.CreateModel(
            name='OpenPorts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.SmallIntegerField()),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosts.host')),
            ],
        ),
    ]
