# Generated by Django 2.2.12 on 2021-10-17 20:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0002_rename_openports_openport'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 17, 20, 49, 38, 748581)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='host',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='openport',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
