# Generated by Django 2.2.12 on 2021-08-30 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_host"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="host",
            name="inci_date",
        ),
    ]
