# Generated by Django 2.2.12 on 2021-08-31 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_remove_host_inci_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='inci_time',
            field=models.DateTimeField(),
        ),
    ]
